### ISSUE TITLE
Apparently not supported for Windows

### ISSUE THREAD

**Issue by CursedSeraphim** [KawaiiKraken/GLaDOS-GPT#11]
If I am not mistaken and as far as I can see, there's a long rabbit hole of chain requirements that need to be installed until you get to the point where there are no install instructions / makefiles / open issues in the https://github.com/espeak-ng/pcaudiolib package.

When installing This GLaDOS-GPT repo I found I did not have something called "espeak" installed. https://github.com/espeak-ng/espeak-ng/tree/master this requires various other things https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#windows 
"Windows - Dependencies - To build eSpeak NG on Windows, you will need:

a copy of [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) or later, such as the Community Edition;
the Windows 8.1 SDK;
the [WiX installer](http://wixtoolset.org/) plugin;
the [pcaudiolib](https://github.com/espeak-ng/pcaudiolib) project checked out to src (as src/pcaudiolib)."

and finally pcaudiolib doesn't actually have the windows installation instructions or makefiles as initially mentioned.

If I am missing something, and this can be easily installed on Windows as well, let me know. Otherwise it might be useful to mention this in the readme.

**Comment by KawaiiKraken** [comment]
the espeak windows installer can be downloaded from https://github.com/espeak-ng/espeak-ng/releases/
its the .msi files
it being 32 or 64 bit may matter, not tested
you will also likely have to add the espeak directory to the path or have an enviroment variable that links to the DLLs specifically just because windows
